### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by bit-scientist** [akshaychawla/ImageNet-downloader#1]
after cloning this into a my local folder I opened cmd command from that directory and typed  `python browse_classes.py -->dog`  and got result 
```
Traceback (most recent call last):
  File "browse_classes.py", line 13, in <module>
    query = raw_input("-->")
NameError: name 'raw_input' is not defined
```
Am I missing something here?

PS: I put parentheses in lines 17 and 18 to match with Python 3.x

**Comment by pangoro24** [comment]
did you solve the problem?
I am getting the same error

**Comment by akshaychawla** [comment]
Hey @git-sohib and @pangoro24 , sorry for the late reply. 
In python3 they have replaced "raw_input" with just "input" as of PEP 3111. 
I think that should fix the issue temporarily. Let me know if it works and I'll close this issue.

**Comment by pangoro24** [comment]
@akshaychawla thanks. Problem solved.
